base/api/urls.py
from django.urls import path 
from . import views  

urlpatterns  = [
    path('',views.getRoutes),
    path('rooms/',views.getRooms),
    path('rooms/<str:pk>/',views.getRooms),

]

base/urls.py
from django.urls import path
from . import views  # we have imported views from base/views.py  that is in the same directory, so we used "." to import from the same directory
# import class based views
# from .views import homepageBeforeLogin
from django.conf import settings
from django.conf.urls.static import static
# from .views import homepageBeforeLogin



############  here we have made a list of url paterns    ###############
urlpatterns  = [
    path('login/',views.UserLogin,name = "UserLogin"),
    path('logout/'   ,views.UserLogout,name = "UserLogout"),
    path('register/' , views.registerUser,name = 'register'),
    
    # path('', views.homepageBeforeLogin, name='homepageBeforeLogin'),
    # the path() function takes 3 arguments: 1st is the url, 2nd is the view function, 3rd is the name of the url  #  the name is optional, but it is good to use it
    # path('', homepageBeforeLogin.as_view(), name='homepageBeforeLogin'),
    # path('home', views.home, name='home'),
    path('', views.homepage,name = 'home'),
    path('Update-User', views.UpdateUser, name='UpdateUser'),
    

    path('room/<str:pk>/',views.room, name ="room"),   # 'pk' stands for Primary Key  and it is set as string.......
    path('UserProfile/<str:pk>',views.UserProfile, name = "UserProfile"),  # url of the user profile page
    path('create-room/',views.CreateRoom, name = "create-room"),  # url of the create room page
    path('update-room/<str:pk>',views.UpdateRoom, name = "update-room") , # url of the update room page
    path('delete-room/<str:pk>',views.DeleteRoom, name = "delete-room"),  # url of the deleteRoom page
    path('join-room/<str:pk>',views.JoinRoom, name = "join-room"),  
    
    path('add-bookmark/<int:room_id>/', views.add_bookmark, name='add-bookmark'),
    path('remove-bookmark/<int:room_id>/', views.remove_bookmark, name='remove_bookmark'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    # path('',views.DeleteRoom, name = "delete-room"),  # url of the deleteRoom page
    path('delete-message/<str:pk>',views.DeleteMessage, name = "delete-message"),  # url of the deleteMessage
    path('topics/', views.topicsPage, name="topics"),
    # path('topics/load_more/', views.load_more_topics, name='load_more_topics'),

    ]

studyBud/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404
from django.shortcuts import render
from django.conf.urls import handler500




# from django.http import HttpResponse

# def home(request):
#     return HttpResponse("Home page")

# def room(request):
#     return HttpResponse("Room page")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ("base.urls") ),
    path('api/', include ("base.api.urls") ),# any url that starts with 'api/' will be redirected to the urls.py file in the base/api directory
    
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)  # this is used to serve the media files in the development server  # this is used to serve the media files in the development server 
urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)  # this is used to serve the media files in the development server  # this is used to serve the media files in the development server 
# def custom_404_view(request, exception):
#     return render(request, '404.html', status=404)

# handler404 = custom_404_view

# def custom_500_view(request):
#     return render(request, '500.html', status=500)

# handler500 = custom_500_view

base/models.py
from django.db import models
from django.contrib.auth.models import  AbstractUser
# from django.contrib.auth.models import User    # this is a django built in model that we will be using to connect the room with the user


class User(AbstractUser):
    # pass   # we use pass when we do not want to write anything in the class
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=200, unique=True)
    headline = models.CharField(max_length=200, null = True, blank = True)
    date_joined = models.DateTimeField(auto_now_add=True,null = True)
    last_login = models.DateTimeField(auto_now=True,null = True)

    Pfp = models.ImageField(default= 'images/avatar.svg',null=True)  # using pip install Pillow to install the pillow library to use the ImageField
   

    USERNAME_FIELD = 'email' # specifying the email as the username field helps us to login using the email instead of the username, which django use username by default for the authentication of the users(login and signup)
    REQUIRED_FIELDS = []
    def __str__(self):
        return self.username
   
# # Create your models here.

##  This is the model for the topic that we will be creating
class Topic(models.Model):
    name = models.TextField(max_length=100)    
   
    def __str__(self):
        return self.name

# This is the model for the room that we will be creating
class Room(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null = True, blank = True)   #  setting to null means that it will be blank in the database if not filled out at runtime otherwise the data basebase will consider it as missing data   # blank means that it is not required to be filled out at runtime 

    participants = models.ManyToManyField(User, related_name = 'participants', blank = True)  # this is the many to many field that we will be using to connect the room with the user, related_name is used to access the participants of the room from the user model, blank means that it is not required to be filled out at runtime

    host = models.ForeignKey(User, on_delete =  models.SET_NULL, null = True)   # when the host is deleted then all its rooms are delete as well
    topic = models.ForeignKey(Topic, on_delete =  models.SET_NULL, null = True)   # when the topic is deleted then all the rooms of that topic will be deleted as well
    updated = models.DateTimeField(auto_now=True)  # auto_now will update the time whenever the room is updated
    created = models.DateTimeField(auto_now_add=True)  # auto_now_add will update the time only when the room is created for the first time
    
    

    def __str__(self):
        return self.name
    
    
    #DECLARING THE CLASS HERE THAT WILL BE USEFULL TO IMPLEMENT SOME OPERATIONS ON THE SPECIFIC MODULE
    class Meta:
        ordering = ['-updated','-created']   # here we are ordering the rooms according to the most recent updated and created room in the list..     The ( - ) sign means to update according to most recent....


##  This is the model for the message that we will be creating
class Message(models.Model):
    user = models.ForeignKey(User, on_delete =  models.CASCADE)   # when the user is deleted then all its messages are delete as well
                # WHEN       USER IS DELETED THEN DELETE ALL MESSAGES
    body = models.CharField(max_length=1000)  # the body of the message
    room = models.ForeignKey(Room, on_delete =  models.CASCADE) 
                # WHEN       ROOM IS DELETED THEN DELETE ALL MESSAGES 
    # THE RELATION OF ROOM TO MESSAGES WILL BE (ONE TO MANY)this is the foreign key that we will be using to connect the message with the room, on_delete=models.CASCADE means that if the room is deleted then the message will also be deleted
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:                       # using this we can order the messages according to the most recent message
        ordering = ['-updated','-created'] #So we do not have to write ordering syntax again and again in the views.py file for everytime we get the messages of the room

    def __str__(self):
        return self.body[:50] # this will return the first 50 characters of the message body




class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user', 'room']  # Ensure a user can't bookmark the same room twice

    def __str__(self):
        return f"{self.user.username} bookmarked {self.room.name}"

base/forms.py
from django.forms import ModelForm
from .models import Room,User
from django.contrib.auth.forms import UserCreationForm #importing the UserCreationForm from the django built in forms. This form will be used to create a form for the user model, 

# from django.contrib.auth.models import User   #importing the user model from the django built in models

class MyUserCreationForm(UserCreationForm):   #  creating a class that inherits properties from the UserCreationForm class,,,, We will 
    class Meta:
        model = User
        fields = ['username','email','password1','password2']  # this will create a form with all the fields of the User model,,,we can also take specific fields from the model and create a form with those fields only
    
    #creating a class that inherits properties from the UserCreationForm class,,,, We will
class UserForm(ModelForm):  #creating a class that inherits properties from the ModelForm class,,,, We will use it in the UpdateUser View.. To make a form that will include all the fields of the user model.
    class Meta:
        model = User
        fields = ['username','email','Pfp','headline']  # this will create a form with all the fields of the User model,,,we can also take specific fields from the model and create a form with those fields only



## this is a RoomForm where we will be creating the form for the room model(containing the fields of the room model)
class RoomForm (ModelForm):
    class Meta:
        model = Room  
        # model = Room
        fields = '__all__'  # this will create a form with all the fields of the Room model,,,we can also take specific fields from the model and create a form with those fields only
        exclude =[ 'host']

base/api/views.py
from django.http import JsonResponse  # importing the JsonResponse which will be used to return the response in the form of json.
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])  # here we are using the api_view decorator to specify the type of request that the view function can handle. In this case, it can handle the GET request.
def getRoutes(request):
    routes =[
        'GET /api/', 
        'GET /api/rooms',  
        'GET /api/rooms/:id' 
    ]
    return Response(routes)

    #return JsonResponse(routes, safe=False)  # here we are returning the response in the form of json, The JSON response will convert the data in the view into JSON data. Safe = False allow us to use data other than the python dictionaries in our response. 

@api_view(['GET'])
def getRooms(request,pk):
    # rooms = Room.objects.all()
    # serializer = RoomSerializer(rooms, many=True) # here we are using the RoomSerializer to convert the rooms object into a JSON object. The many=True argument is used to specify that we are serializing a queryset, not a single instance... many = True is use to serialize multiple objects
   
    # # here we are passing the rooms object to the Response... The response can't take python objects as arguments, so we have to convert the rooms object into a dictionary using the serializer...
    # return Response(serializer.data)

    room = Room.objects.get(id = pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)  # here we are passing the room object to the Response... The response can't take python objects as arguments, so we have to convert the room object into a dictionary using the serializer...
  

base/templates/base/UpdateUser.html
{% extends 'main.html' %}

{% block content %}
<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'UserProfile' request.user.id %} ">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Edit your profile</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST" enctype="multipart/form-data">   
          <!-- setting the enctype  to multipart/form-data is necessary for file uploads In a form. It tells django that a user is submitting some Files in the form along with other Fields 
          ALSO WE WRITE THE REQUEST.FILES IN THE VIEW TO PROCESS THE FILES OPLOAD IN A FORM -->
          {% csrf_token %}

          {% for field in form %}
          <div class="form__group">
            <label for="profile_pic"> {{field.label}} </label> 
            {{field}}


            {% comment %} {% if field.help_text %}
            <span > {{field.help_text}}</span>
            {% endif %}  {% endcomment %}
            

          </div>

          {% endfor %}


          <div class="form__action">
            <a class="btn btn--dark" href="{% url 'UserProfile' request.user.id %} ">Cancel</a>  
            <button class="btn btn--main" type="submit">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock content %}

base/templates/base/UserLogin_old.html
{% include "main.html" %}


{%if page == 'login' %}
<div> 
    <form method = "POST" action ="">
        {% csrf_token %}
        <label>UserName:</label>
        <input type = "text" name="username" placeholder = "Enter Username"/>
        <label>Password:</label>
        <input type = "password" name="password" placeholder = "Enter Password"/>
        
        <input type ="submit" name = "Login">
    </form>
    <p>haven't signed up yet?</p>
    <a href = "{%url 'register'%}">SIgn UP </a>
        
</div>


{%else%}   
{% comment %} For Registering the User if it is not already in the data base {% endcomment %}
<div>
    <form method = "POST" action ="">
        {% csrf_token %}
        
        <input type ="submit" name = "register">
        {{form.as_p}} {% comment %} here we are creating the form for registering the user  {% endcomment %}
    </form>
    <p> Already signed up ?</p> 

    <a href = "{%url 'UserLogin' %}">Login</a>
   
</div>
{%endif%}

base/templates/base/activityComponent.html
 <!--   RECENT ACTIVITIES-->
<div class="activities">

  <div class="activities__header"> <!--THE HEADER OF ACTIVITIES  SECTION -->
      <h2>Recent Activities</h2>
  </div>

    {% for message in UserMessages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'UserProfile' message.user.id %}" class="roomListRoom__author">

                <div class="avatar avatar--small">
                    <img src="{{message.user.Pfp.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} ago</span>
                </p>
            </a>

      <!-- If the   USER IS THE USER WHO SENT THE MESSAGE, THEN HE CAN DELETE THE MESS THROUGHT THE CROSS AT TOP -->
            {% if request.user == message.user %}
               <div class="roomListRoom__actions">
                   <a href="{% url 'delete-message'  message.id %}">
                       <svg version="1.1" xmlns="http:// www.  w3.org/2000/svg" width="32"    height="32" viewBox="0 0 32 32">
                           <title>remove</title>
                           <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                           </path>
                       </svg>
                   </a>
               </div>
            {% endif %}

        </div>

        <!-- THE ACTUAL MESSAGE  CONTENTS -->
        <div class="activities__boxContent">
            <p>replied to a post in 
                <br>
                <span>“<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</span>
            </p>
            <div class="activities__boxRoomContent">{{message.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>

























{% comment %} 

{% block content%}
{% for UserMessage in UserMessages %}
        <div>
          <small> <a href = "{% url 'UserProfile' UserMessage.user.id%}">@{{UserMessage.user}}</a>  ({{UserMessage.created|timesince}}) replied in "<a href= "{% url 'room' UserMessage.room.id%} ">{{UserMessage.room}}" </a></small>
          <br>

          <small><li>{{UserMessage}}</li></small>
          {% if request.user == UserMessage.user %} 
          <a href = "{% url 'delete-message' UserMessage.id %}">Delete</a>
          {% endif%}
          <hr>
        </div>
{% endfor%}
{% endblock content%} {% endcomment %}

base/templates/base/bookmarks.html
{% load static%}
{% include 'main.html'%}
{% block content%}









<div class="roomListRoom__meta">
        
    <div class="bookmark-heading-main">
      <h1>Your Bookmarks</h1>
    </div>    
        {% if bookmarks %}
        <ul>
            {% for bookmark in bookmarks %}
                <li>
                    {% comment %} <a href="{% url 'room' bookmark.room.id %}">{{ bookmark.room.name }}</a>
                    <a href="{% url 'remove_bookmark' room_id=bookmark.room.id %}">
                        <button class="btn-remove">Remove Bookmark</button>
                    </a> {% endcomment %}
                    <a href="{% url 'room' bookmark.room.id %}">{{ bookmark.room.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have no bookmarked rooms.</p>
    {% endif %} {% comment %} getting the count of the participants in the room as it is a many to many field {% endcomment %}
    </a>
    <p class="roomListRoom__topic">{{room.topic.name}}</p>   {% comment %} getting the topic of the roooom {% endcomment %}
 </div>
 

{% endblock content %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">   <!-- This will take the user to the  page they came from... IT is an ARROW -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/home.html
{% extends "main.html" %}

{% block content %}
{% include 'preloader.html'%}
<main class="layout layout--3">
  <div class="container">
   
    <!-- Topics Start -->
    {% include 'base/topicsComponents.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>Search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for anything..." />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="activity">Recent Activities</a>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Rooms</h2>
          <p>{{ room_count }} Rooms available</p>
        </div>

        <!-- Create a Room Button -->
        <button class="btn btn--main create-room-btn" id="create-room-btn">
          <span class="btn-text">Create a Room</span>
          <span class="spinner hidden"></span>
        </button>
      </div>

      {% include 'base/feedComponent.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activityComponent.html' %}
    <!-- Activities End -->
  </div>
</main>

<style>
  /* Button Loading Spinner Styles */
  .create-room-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    transition: background 0.3s ease;
  }

  .create-room-btn .btn-text {
    transition: opacity 0.3s ease;
  }

  .create-room-btn .spinner {
    position: absolute;
    width: 24px;
    height: 24px;
    border: 3px solid transparent;
    border-top-color: #00f2fe;
    border-right-color: #4facfe;
    border-radius: 50%;
    animation: spin 1s linear infinite, glow 1.5s ease-in-out infinite;
    visibility: hidden;
  }

  .create-room-btn.loading .btn-text {
    opacity: 0;
  }

  .create-room-btn.loading .spinner {
    visibility: visible;
  }

  /* Gradient Glow Effect */
  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  @keyframes glow {
    0%, 100% {
      box-shadow: 0 0 10px #4facfe, 0 0 20px #00f2fe;
    }
    50% {
      box-shadow: 0 0 20px #00f2fe, 0 0 30px #4facfe;
    }
  }
</style>

<script>
  document.getElementById("create-room-btn").addEventListener("click", function (event) {
    // Prevent default action
    event.preventDefault();

    // Add loading class to the button
    const button = event.target.closest(".create-room-btn");
    button.classList.add("loading");

    // Simulate a delay, then redirect
    setTimeout(() => {
      button.classList.remove("loading"); // Remove loading class after redirection
      window.location.href = "{% url 'create-room' %}";
    }, 1500); // Adjust delay if needed
  });
</script>
{% endblock %}

base/templates/base/profileComponent.html
 <!--   RECENT ACTIVITIES-->
{% block content%}

 <div class="activities">

    <div class="activities__header"  > <!--THE HEADER OF ACTIVITIES  SECTION -->
        <h2 style="display: flex; align-items: center; justify-content: center;" >About&nbsp; <strong>{{request.user.username}}</strong></h2>
    </div>
    <div> 
        <div class="profile-info-container">
            <div class="profile__avatar ">
                <div class="avatar avatar--small active">
                    <img src="{{request.user.Pfp.url}}" />
                </div>
            </div>
            <div class="profile__info">
                <p>@{{request.user.username}}</p>
                <div class= "profile-info-headline">
                   {% if  request.user.headline is not none%}
                      <p>::{{request.user.headline}}</p>
                   {% else%}
                      <a href="{% url 'UpdateUser' %}"><p> Enter Bio/Headline</p></a>
                   {% endif%}
                </div>
                
            </div>
       </div>

        <div class="profile-details-container">
            {% comment %} <h3 style="display: flex; align-items: center; justify-content: center; font-size: 18px;">About</h3> {% endcomment %}
        
            {% comment %} <hr class= "profile-details-hr"> {% endcomment %}

          <div class="profile-details">

            <div class= "profile-details-info">
                <h6> {{request.user.room_set.count}}</h6>
                
                <span>Rooms</span>
            </div>
            <hr class= "profile-details-hr">
            <div class= "profile-details-info">
               <h6> {{request.user.date_joined|date:"F d, Y"}}</h6>
               
               <span>Joined</span>

            </div>
            <hr class= "profile-details-hr">

            <div class= "profile-details-info">
                <h6>{{request.user.last_login|date:"F d, Y"}}</h6>
                
                <span>Last Active</span>
            </div>
            
          </div>
        </div>

    </div>
    <hr class= "profile-details-hr">

    <div class="social-links">
        
        <ul class="social-list">

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-instagram"></ion-icon>
                <ion-icon name="logo-instagram"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-reddit"></ion-icon>
                <ion-icon name="logo-reddit"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-discord"></ion-icon>
                <ion-icon name="logo-discord"></ion-icon>
              </a>
            </li>

          </ul>
    </div>
  
  </div>
  
  
  {% endblock content%}
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

base/templates/base/room_form_old.html
{% block content %}


<div>
    <form method = "POST" action ="">
    {% csrf_token %}    {% comment %} # cross site request forgery  {% endcomment %}
    {{form.as_p}}     {% comment %} # form.as_p is a shortcut for rendering each field as a paragraph {% endcomment %}
    <input type = "submit" value = "Submit"/>
    </form>
</div>

{% endblock content %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"></path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <!-- Search form -->
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <!-- List of topics -->
        <ul id="topics-list" class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{ topics.count }}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }} <span>{{ topic.room_set.all.count }}</span></a>
          </li>
          {% endfor %}
        </ul>

        <!-- Load More Button -->
        <button id="load-more" class="btn btn--link">Load More</button>
      </div>
    </div>
  </div>
</main>

{% endblock content %}


{% comment %} <script>
  document.addEventListener('DOMContentLoaded', function() {
    let page = 2;  // Start from the second page

    // Load more button click event
    document.getElementById('load-more-btn')?.addEventListener('click', function() {
      let url = "{% url 'topics' %}?page=" + page;  // URL to fetch next page of topics
      let searchQuery = document.querySelector('input[name="q"]').value;
      if (searchQuery) {
        url += "&q=" + searchQuery;  // Include search query if present
      }

      // Perform AJAX request to load more topics
      fetch(url, {
        method: 'GET',
        headers: {
          'X-Requested-With': 'XMLHttpRequest',
        },
      })
      .then(response => response.json())
      .then(data => {
        const topicsList = document.getElementById('topics-list');
        data.topics.forEach(topic => {
          const listItem = document.createElement('li');
          listItem.innerHTML = `<a href="{% url 'home' %}?q=${topic.name}">${topic.name} <span>${topic.count}</span></a>`;
          topicsList.appendChild(listItem);
        });

        // Check if there are more topics to load
        if (data.has_next) {
          page++;
        } else {
          // Remove "Load More" button if no more pages
          document.getElementById('load-more-btn').remove();
        }
      })
      .catch(error => {
        console.error('Error loading more topics:', error);
      });
    });
  });
</script> {% endcomment %}